package riscv

import chisel3._
import chiseltest._
import org.scalatest.flatspec.AnyFlatSpec

import riscv.shared.Constants._

class ProcessorTest extends AnyFlatSpec with ChiselScalatestTester {

  "ProcessorTest" should "pass" in {
    test(new Processor) { dut =>
      dut.io.instr.poke("h7000093".U)
      dut.clock.step()
      dut.io.instr.poke("h00112e23".U)
      dut.clock.step()
      dut.clock.step()
      dut.clock.step()
      dut.io.instr.poke("h00812c23".U)
      dut.clock.step()
      dut.io.instr.poke("h02010413".U)
      dut.clock.step()
      dut.io.instr.poke("h00500793".U)
      dut.clock.step()
      dut.io.instr.poke("hfef42623".U)
      dut.clock.step()
      dut.io.instr.poke("h00200793".U)
      dut.clock.step()
      dut.io.instr.poke("hfef42423".U)
      dut.clock.step()
      dut.io.instr.poke("hfe842583".U)
      dut.clock.step()
      dut.io.instr.poke("hfec42503".U)
      dut.clock.step()
      dut.io.instr.poke("h024000ef".U)
      dut.clock.step()
      dut.io.instr.poke("h00050613".U)
      dut.clock.step()
      dut.io.instr.poke("h00000513".U)
      dut.clock.step()
      dut.io.instr.poke("h0015f693".U)
      dut.clock.step()
      dut.io.instr.poke("h00068463".U)
      dut.clock.step()
      dut.io.instr.poke("h0015d593".U)
      dut.clock.step()
      dut.io.instr.poke("h00161613".U)
      dut.clock.step()
      dut.io.instr.poke("hfe0596e3".U)
      dut.clock.step()
      dut.io.instr.poke("h00000513".U)
      dut.clock.step()
      dut.io.instr.poke("h0015f693".U)
      dut.clock.step()
      dut.io.instr.poke("h00c50533".U)
      dut.clock.step()
      dut.io.instr.poke("h0015d593".U)
      dut.clock.step()
      dut.io.instr.poke("h00161613".U)
      dut.clock.step()
      dut.io.instr.poke("hfe0596e3".U)
      dut.clock.step()
      dut.io.instr.poke("h00008067".U)
      dut.clock.step()
      dut.io.instr.poke("h00050793".U)
      dut.clock.step()
      dut.io.instr.poke("hfef42223".U)
      dut.clock.step()
      dut.io.instr.poke("h00000793".U)
      dut.clock.step()
      dut.io.instr.poke("h00078513".U)
      dut.clock.step()
      dut.io.instr.poke("h01c12083".U)
      dut.clock.step()
      dut.io.instr.poke("h01812403".U)
      dut.clock.step()
      dut.io.instr.poke("h02010113".U)
      dut.clock.step()
      dut.io.instr.poke("h00008067".U)
      dut.clock.step()
      dut.io.instr.poke("h40000F13".U)
      dut.clock.step()
      dut.io.instr.poke("h0400F2F03".U)
      dut.clock.step()
      // dut.clock.step()
      // dut.clock.step()
      // dut.io.instr.poke("h00000FEF".U)
      // dut.clock.step()

      println("instrAddrs " + dut.io.instrAddrs.peek().toString)
      println("memAdrrs " + dut.io.memAdrrs.peek().toString)
      println("memWriteBlock " + dut.io.memWriteBlock.peek().toString)
      println("memRead " + dut.io.memRead.peek().toString)
      println("memWrite " + dut.io.memWrite.peek().toString)
      

    }
  }
}

